# Generated by Django 2.0 on 2017-12-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=10)),
                ('sizes', models.CharField(max_length=3)),
                ('stock', models.SmallIntegerField()),
            ],
        ),
    ]
