# Generated by Django 2.0 on 2017-12-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',)},
        ),
    ]
