# Generated by Django 2.0 on 2017-12-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20171214_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women')], default='MEN', max_length=5),
        ),
    ]
