# Generated by Django 2.0 on 2017-12-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20171214_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='clothingtype',
            field=models.CharField(choices=[('SHOE', 'Shoes'), ('CLOTHING', 'Clothes')], default='CLOTHING', max_length=8),
        ),
    ]
