# Generated by Django 2.0 on 2017-12-14 13:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20171214_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('36', '36 EU'), ('37', '37 EU'), ('38', '38 EU'), ('39', '39 EU'), ('40', '40 EU'), ('41', '41 EU'), ('42', '42 EU'), ('43', '43 EU'), ('44', '44 EU'), ('45', '45 EU'), ('46', '46 EU'), ('47', '47 EU'), ('48', '48 EU')], default='M', max_length=50),
        ),
    ]
